config/routes.rb
Rails.application.routes.draw do
  get 'dashboard', to: 'dashboards#show', as: 'dashboard'

  resources :players, :rounds, :boxes

  post '/status', to: 'players#status', as: 'status'

  get '/signup', to: 'players#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :player
  belongs_to :box
end

app/models/box.rb
class Box < ApplicationRecord
  belongs_to :round
  has_many :assignments
  has_many :players, through: :assignments, dependent: :destroy

  def current
    self.round.current?
  end

end

app/models/player.rb
class Player < ApplicationRecord
  attr_accessor :remember_token

  has_many :assignments
  has_many :boxes, through: :assignments, dependent: :destroy

  has_secure_password

  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :first_name, presence: true
  validates :password, presence: true, length: { minimum: 6 }, on: :create

  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
  
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # returns hash digest of given string
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def remember
    self.remember_token = Player.new_token
    update_attribute(:remember_digest, Player.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def active?
    active
  end

end

app/models/round.rb
class Round < ApplicationRecord
  has_many :boxes

  def self.current
    self.find { |r| r.current? }
  end

  def current?
    Date.current > start_time && Date.current < end_time
  end

  def end_time
    start_time + duration
  end
end

app/models/venue.rb
class Venue < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  before_action :set_raven_context

  def index
    if logged_in?
      redirect_to dashboard_path
    else
      redirect_to login_path
    end
  end

  private

  def set_raven_context
    unless session[:player_id].nil?
      Raven.user_context(id: session[:player_id], email: current_user.email) # or anything else in session
    end
    Raven.extra_context(params: params.to_unsafe_h, url: request.url)
  end

end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  def show
    @box = Box.find(params[:id])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @dashboard = Dashboard.new(current_user)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :check_login, :find_player, only: %i[edit show update status]
  before_action :authorize, only: %i[edit update status]

  def index
    @players = Player.active
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      flash.now[:success] = 'Welcome to BonsorBox!'
      redirect_to @player
    else
      render 'new'
    end
  end

  def new
    @player = Player.new
  end

  def show
  end

  def edit
  end

  def update
    if @player.update(player_params)
      flash.now[:success] = 'Profile updated.'
    else
      flash.now[:danger] = 'Could not update your profile.'
    end
    render 'edit'
  end

  def destroy
  end

  def status
    byebug
    p = Players::UpdateStatus.new(@player)
    if p.save
      flash.now[:success] = 'Your status has been updated.'
    else
      flash.now[:danger] = 'Your status could not be updated.'
    end
    render 'edit'
  end

  private

  def check_login
    unless logged_in?
      flash[:danger] = 'You must be logged in to do that.'
      redirect_to login_path
    end
  end

  def authorize
    unless current_user?(@player)
      flash[:danger] = 'You are not authorized to do that.'
      redirect_to root_path
    end
  end

  def find_player
    @player = Player.find(params[:id])
  end

  def player_params
    params.require(:player).permit(:first_name, :last_name, :email, :phone, :preferred_contact, :password, :password_confirmation)
  end

end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  def index
    @rounds = Round.all
  end

  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    player = Player.find_by(email: params[:session][:email].downcase)

    if player && player.authenticate(params[:session][:password])
      log_in player
      params[:session][:remember_me] == '1' ? remember(player) : forget(player)
      redirect_to dashboard_path
    else
      flash.now[:danger] = 'Invalid email or password'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    flash.now[:success] = "You have been logged out."
    redirect_to login_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def logger
    @logger ||= Rails.logger
  end

  def current_round
    Round.current
  end

  def time_to_round_end
    distance_of_time_in_words_to_now(current_round.end_time)
  end

  def current_round_end
    Round.current.end_time.strftime('%A, %b %e')
  end

  def format_preferred_contact(player)
    if player.preferred_contact.empty?
      "text or email"
    else
      player.preferred_contact.capitalize
    end
  end

  def full_name(player)
    "#{player.first_name} #{player.last_name}"
  end

end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
  def status(player)
    player.active ? 'active' : 'inactive'
  end

  def status_button(player)
    player.active ? 'inactive' : 'active'
  end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(player)
    session[:player_id] = player.id
  end

  def remember(player)
    player.remember
    cookies.permanent.signed[:player_id] = player.id
    cookies.permanent[:remember_token] = player.remember_token
  end

  def current_user
    if (player_id = session[:player_id])
      @current_user ||= Player.find_by(id: player_id)
    elsif (player_id = cookies.signed[:player_id])
      player = Player.find_by(id: player_id)
      if player && player.authenticated?(cookies[:remember_token])
        log_in player
        @current_user = player
      end
    end
  end

  def current_user?(user)
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(player)
    player.forget
    cookies.delete(:player_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:player_id)
    @current_user = nil
  end
end

app/views/boxes/show.html.erb
<h1>Box <%= @box.id %></h1>
<p>
  <ul>
    <% @box.players.each do |p| %>
      <li><%= p.full_name %></li>
    <% end %>
  </ul>
</p>

app/views/dashboards/show.html.erb
<% if current_user.active? %>
  <h1 class="display-3">Your box</h1>
  <h3>Round ends in <%= time_to_round_end %> at midnight on <%= current_round_end %></h3>
  <% if @dashboard.current_box %>
    <div class="row">
    <% @dashboard.opponents.each do |o| %>
        <div class="col-sm-12 col-md-6 col-lg-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title"><%= link_to full_name(o), player_path(o.id) %></h5>
              <h6 class="card-subtitle"><%= o.email %></h6>
              <h6 class="card-subtitle"><%= o.phone %></h6>
              <p class="card-text">Prefers <%= format_preferred_contact(o) %></p>
            </div>
          </div>
        </div>
    <% end %>
    </div>
  <% else %>
    <h5>You have not been assigned to a box this round.</h5>
  <% end %>
<% else %>
  <h3>You are currently inactive. You will not be assigned opponents. Do you want to go active?</h3>
  <button class="btn btn-primary">Yes, activate me</button>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
  <%= link_to "BonsorBox", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <% if logged_in? %>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active"><%= link_to "Dashboard", dashboard_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "Profile", edit_player_path(current_user), class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "Players", players_path, class: "nav-link" %></li>
    </ul>
    <div class="col-auto navbar-text">
      Your status: <%= status(current_user) %>
    </div>
    <div class="col-auto">
      <%= link_to "Logout", logout_path, method: :delete, class: "btn btn-block btn-secondary" %>
    </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BonsorBox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |type, msg| %>
        <div><%= msg %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_for @player do |f| %>
  <%= render 'shared/error_messages' %>
  
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :phone %>
  <%= f.phone_field :phone %>

  <%= f.radio_button :preferred_contact, "email" %>
  <%= f.label :preferred_contact, "Email" %>

  <%= f.radio_button :preferred_contact, "text" %>
  <%= f.label :preferred_contact, "Text" %>

  <%= f.label :notes, "Availability" %>
  <%= f.text_area :notes %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit yield(:button_text) %>
<% end %>

app/views/players/_update_status.html.erb
	You are <%= status(@player) %>.
	<%= link_to "Set status to #{status_button(@player)}", status_path(id: @player.id), method: :post, class: 'btn btn-primary' %>

app/views/players/create.html.erb
<h1>Players#create</h1>
<p>Find me in app/views/players/create.html.erb</p>

app/views/players/destroy.html.erb
<h1>Players#destroy</h1>
<p>Find me in app/views/players/destroy.html.erb</p>

app/views/players/edit.html.erb
<% provide(:button_text, 'Submit changes') %>
<h1 class='display-3'>Update your information</h1>
<h3>
	<%= render 'update_status', locals: { player: @player } %>
</h3>
<h3>Edit your profile</h3>
<%= render 'form' %>

app/views/players/index.html.erb
<h1 class="display-3">Active player list</h1>
  <ul>
  <% @players.each do |p| %>
    <li><%= link_to p.full_name, player_path(p.id) %> - <%= p.email %></li>
  <% end %>
</ul>

app/views/players/new.html.erb
<% provide(:button_text, 'Create my account') %>
<h1 class="display-3">Create your profile</h1>
<%= render 'form' %>

app/views/players/show.html.erb
<% provide(:title, @player.full_name) %>

<h1 class="display-3"><%= @player.full_name %></h1>
<p><strong>Email:</strong> <%= mail_to @player.email %></p>
<p><strong>Text/phone:</strong> <%= @player.phone %></p>
<p><strong>Preferred contact method:</strong> <%= format_preferred_contact(@player) %></p>
<h3>Availability</h3>
<p><%= @player.notes %>

app/views/rounds/index.html.erb
<h1>Rounds#index</h1>
  <ul>
  <% @rounds.each do |r| %>
    <li><strong><%= r.start_date.to_s %></strong></li>
    <% r.boxes.each do |b| %>
      <li><%= link_to "Box", box_path(b) %></li>
    <% end %>
  <% end %>
</ul>

app/views/rounds/show.html.erb
<h1>Rounds#show</h1>
<p>Find me in app/views/rounds/show.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if !@player.errors.empty? %>
  <ul>
  <% @player.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>